// =============================================================================
// Mixed-Precision FFT Core – 1024-point FULLY PIPELINED II=1 ARCHITECTURE
// Auto-generated by FFTTemplateGenerator
// Active-low asynchronous reset (negedge rst).
// =============================================================================
`timescale 1ns/1ps

module fft_1024_sol3_gen2_core #(
    parameter MAX_N      = 1024,
    parameter ADDR_WIDTH = 11
)(
    input  wire        clk,
    input  wire        rst,     // active-low async reset

    // Control Channels
    input  wire        start,
    output reg         done,

    // External Load Interface
    input  wire                  ext_wr_en,
    input  wire [ADDR_WIDTH-1:0] ext_wr_addr,
    input  wire [23:0]           ext_wr_data,

    // External Unload Interface
    input  wire                  ext_reading,
    input  wire [ADDR_WIDTH-1:0] ext_rd_addr,
    output wire [15:0]           ext_rd_data,

    input  wire                  ext_bank_sel
);

    localparam STAGE0_MULT_PREC = 0;
    localparam STAGE0_ADD_PREC  = 0;
    localparam STAGE0_OUT_PREC  = 0;
    localparam STAGE1_MULT_PREC = 0;
    localparam STAGE1_ADD_PREC  = 0;
    localparam STAGE1_OUT_PREC  = 0;
    localparam STAGE2_MULT_PREC = 0;
    localparam STAGE2_ADD_PREC  = 0;
    localparam STAGE2_OUT_PREC  = 0;
    localparam STAGE3_MULT_PREC = 0;
    localparam STAGE3_ADD_PREC  = 0;
    localparam STAGE3_OUT_PREC  = 0;
    localparam STAGE4_MULT_PREC = 1;
    localparam STAGE4_ADD_PREC  = 0;
    localparam STAGE4_OUT_PREC  = 0;
    localparam STAGE5_MULT_PREC = 0;
    localparam STAGE5_ADD_PREC  = 0;
    localparam STAGE5_OUT_PREC  = 0;
    localparam STAGE6_MULT_PREC = 0;
    localparam STAGE6_ADD_PREC  = 0;
    localparam STAGE6_OUT_PREC  = 0;
    localparam STAGE7_MULT_PREC = 0;
    localparam STAGE7_ADD_PREC  = 0;
    localparam STAGE7_OUT_PREC  = 0;
    localparam STAGE8_MULT_PREC = 0;
    localparam STAGE8_ADD_PREC  = 0;
    localparam STAGE8_OUT_PREC  = 0;
    localparam STAGE9_MULT_PREC = 0;
    localparam STAGE9_ADD_PREC  = 0;
    localparam STAGE9_OUT_PREC  = 0;

    // Dynamic Context Setup Configurations
    reg cur_mult_prec;
    reg cur_rd_prec;
    reg cur_wr_prec;

    // =========================================================================
    // HIGH-PERFORMANCE STREAMING AGU WITH STALL LOGIC
    // =========================================================================
    reg  start_agu_reg;
    wire streaming_enable;
    wire [ADDR_WIDTH-1:0] idx_a, idx_b, k;
    wire done_stage, done_fft;
    wire [ADDR_WIDTH-1:0] curr_stage;

    reg [5:0] pipeline_stall_cnt;
    wire agu_stall = (pipeline_stall_cnt > 0);
    
    always @(posedge clk or negedge rst) begin
        if (!rst) begin
            pipeline_stall_cnt <= 0;
        end else if (done_stage && !done_fft) begin
            pipeline_stall_cnt <= 12;
        end else if (pipeline_stall_cnt > 0) begin
            pipeline_stall_cnt <= pipeline_stall_cnt - 1;
        end
    end

    dit_fft_agu_streaming #(
        .MAX_N     (MAX_N),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) agu (
        .clk          (clk),
        .reset        (rst),
        .stall        (agu_stall),
        .start        (start_agu_reg),
        .N            (11'd1024),
        .stream_en    (streaming_enable),
        .idx_a        (idx_a),
        .idx_b        (idx_b),
        .k            (k),
        .done_stage   (done_stage),
        .done_fft     (done_fft),
        .curr_stage   (curr_stage)
    );

    always @(*) begin
        if (ext_reading) begin
            cur_mult_prec = 1'b0;
            cur_rd_prec   = 1'b0;
        end else begin
            case (curr_stage[3:0])
            4'd0: begin
                cur_mult_prec = STAGE0_MULT_PREC;
                cur_rd_prec   = 1'b1;
            end
            4'd1: begin
                cur_mult_prec = STAGE1_MULT_PREC;
                cur_rd_prec   = STAGE0_OUT_PREC;
            end
            4'd2: begin
                cur_mult_prec = STAGE2_MULT_PREC;
                cur_rd_prec   = STAGE1_OUT_PREC;
            end
            4'd3: begin
                cur_mult_prec = STAGE3_MULT_PREC;
                cur_rd_prec   = STAGE2_OUT_PREC;
            end
            4'd4: begin
                cur_mult_prec = STAGE4_MULT_PREC;
                cur_rd_prec   = STAGE3_OUT_PREC;
            end
            4'd5: begin
                cur_mult_prec = STAGE5_MULT_PREC;
                cur_rd_prec   = STAGE4_OUT_PREC;
            end
            4'd6: begin
                cur_mult_prec = STAGE6_MULT_PREC;
                cur_rd_prec   = STAGE5_OUT_PREC;
            end
            4'd7: begin
                cur_mult_prec = STAGE7_MULT_PREC;
                cur_rd_prec   = STAGE6_OUT_PREC;
            end
            4'd8: begin
                cur_mult_prec = STAGE8_MULT_PREC;
                cur_rd_prec   = STAGE7_OUT_PREC;
            end
            4'd9: begin
                cur_mult_prec = STAGE9_MULT_PREC;
                cur_rd_prec   = STAGE8_OUT_PREC;
            end
                default: begin
                    cur_mult_prec = 1'b0; cur_rd_prec = 1'b1;
                end
            endcase
        end
    end

    always @(*) begin
        case (curr_stage_delayed[3:0])
            4'd0: begin
                cur_wr_prec   = STAGE0_OUT_PREC;
            end
            4'd1: begin
                cur_wr_prec   = STAGE1_OUT_PREC;
            end
            4'd2: begin
                cur_wr_prec   = STAGE2_OUT_PREC;
            end
            4'd3: begin
                cur_wr_prec   = STAGE3_OUT_PREC;
            end
            4'd4: begin
                cur_wr_prec   = STAGE4_OUT_PREC;
            end
            4'd5: begin
                cur_wr_prec   = STAGE5_OUT_PREC;
            end
            4'd6: begin
                cur_wr_prec   = STAGE6_OUT_PREC;
            end
            4'd7: begin
                cur_wr_prec   = STAGE7_OUT_PREC;
            end
            4'd8: begin
                cur_wr_prec   = STAGE8_OUT_PREC;
            end
            4'd9: begin
                cur_wr_prec   = STAGE9_OUT_PREC;
            end
            default: cur_wr_prec = 1'b0;
        endcase
    end

    // =========================================================================
    // PIPELINED CORDIC TWIDDLE GENERATION ENGINE (ROM-LESS)
    // =========================================================================
    wire [15:0] twiddle;
    localparam CORDIC_LATENCY = 10;

    cordic_twiddle_generator #(
        .LATENCY(CORDIC_LATENCY),
        .MAX_N(MAX_N),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) twiddle_gen (
        .clk        (clk),
        .rst        (rst),
        .k          (k),
        .n          (11'd1024),
        .valid_in   (streaming_enable),
        .PRECISION  (cur_mult_prec),
        .twiddle_out(twiddle)
    );

    // =========================================================================
    // BALANCING TIMING DELAY PIPELINE (II=1 Chain Matrix)
    // =========================================================================
    localparam TOTAL_LATENCY = 11;

    reg [TOTAL_LATENCY-1:0]  wr_en_pipe;
    reg [ADDR_WIDTH-1:0]     wr_addr_a_pipe   [0:TOTAL_LATENCY-1];
    reg [ADDR_WIDTH-1:0]     wr_addr_b_pipe   [0:TOTAL_LATENCY-1];
    reg                      bank_sel_pipe    [0:TOTAL_LATENCY-1];
    reg [ADDR_WIDTH-1:0]     stage_mask_pipe  [0:TOTAL_LATENCY-1];
    reg [ADDR_WIDTH-1:0]     curr_stage_pipe  [0:TOTAL_LATENCY-1];

    reg                      fft_bank_sel;
    wire [ADDR_WIDTH-1:0]    current_rd_mask = (11'b1 << curr_stage);

    integer i;
    always @(posedge clk or negedge rst) begin
        if (!rst) begin
            wr_en_pipe <= 0;
            for (i = 0; i < TOTAL_LATENCY; i = i + 1) begin
                wr_addr_a_pipe[i]  <= 0;  wr_addr_b_pipe[i]  <= 0;
                bank_sel_pipe[i]   <= 0;  stage_mask_pipe[i] <= 0;
                curr_stage_pipe[i] <= 0;
            end
        end else begin
            wr_en_pipe <= {wr_en_pipe[TOTAL_LATENCY-2:0], streaming_enable};
            
            wr_addr_a_pipe[0]  <= idx_a;
            wr_addr_b_pipe[0]  <= idx_b;
            bank_sel_pipe[0]   <= fft_bank_sel;
            stage_mask_pipe[0] <= current_rd_mask;
            curr_stage_pipe[0] <= curr_stage;

            for (i = 1; i < TOTAL_LATENCY; i = i + 1) begin
                wr_addr_a_pipe[i]  <= wr_addr_a_pipe[i-1];
                wr_addr_b_pipe[i]  <= wr_addr_b_pipe[i-1];
                bank_sel_pipe[i]   <= bank_sel_pipe[i-1];
                stage_mask_pipe[i] <= stage_mask_pipe[i-1];
                curr_stage_pipe[i] <= curr_stage_pipe[i-1];
            end
        end
    end

    // Pull aligned execution handles from tail of delay line
    wire                  mem_wr_en       = wr_en_pipe[TOTAL_LATENCY-1];
    wire [ADDR_WIDTH-1:0] mem_wr_addr_a   = wr_addr_a_pipe[TOTAL_LATENCY-1];
    wire [ADDR_WIDTH-1:0] mem_wr_addr_b   = wr_addr_b_pipe[TOTAL_LATENCY-1];
    wire                  mem_wr_bank     = bank_sel_pipe[TOTAL_LATENCY-1];
    wire [ADDR_WIDTH-1:0] mem_wr_mask     = stage_mask_pipe[TOTAL_LATENCY-1];
    wire [ADDR_WIDTH-1:0] curr_stage_delayed = curr_stage_pipe[TOTAL_LATENCY-1];

    // =========================================================================
    // MULTI-BANK TRUE CONCURRENT MEMORY SUBSYSTEM
    // =========================================================================
    wire                  active_rd_bank = ext_reading ? ext_bank_sel : fft_bank_sel;
    wire [ADDR_WIDTH-1:0] mem_rd_addr_a  = ext_reading ? ext_rd_addr  : idx_a;
    wire [ADDR_WIDTH-1:0] mem_rd_addr_b  = ext_reading ? ext_rd_addr  : idx_b;

    wire [15:0] rd_data_a_16, rd_data_b_16;
    assign ext_rd_data = rd_data_a_16;

    mixed_dual_bank_memory_concurrent #(
        .n         (MAX_N),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) mem (
        .clk          (clk),
        .rst          (rst),
        
        // Concurrent Independent Port Reads (Cycle 0 Request Paths)
        .bank_pingpong (active_rd_bank),
        .stage_mask    (11'h001),
        .rd_addr_a     (mem_rd_addr_a),
        .rd_addr_b     (mem_rd_addr_b),
        .rd_precision  (cur_rd_prec),
        .rd_data_a     (rd_data_a_16),
        .rd_data_b     (rd_data_b_16),
        
        // Concurrent Independent Port Writes (Delayed Pipeline Execution Paths)
        .wr_en         (ext_wr_en ? 1'b1 : mem_wr_en),
        .wr_addr_a     (ext_wr_en ? ext_wr_addr : mem_wr_addr_a),
        .wr_addr_b     (ext_wr_en ? ext_wr_addr : mem_wr_addr_b),
        .wr_data_a     (ext_wr_en ? ext_wr_data : X_wr_24),
        .wr_data_b     (ext_wr_en ? ext_wr_data : Y_wr_24),

        .bank_pingpong_wr (ext_wr_en ? 1'b0 : mem_wr_bank),
        .stage_mask_wr    (11'h001)
    );

    // Unpack, decode and extend dual-bank concurrent memory lanes
    wire [7:0]  rd_a_fp8_as_fp4, rd_b_fp8_as_fp4;
    complex_fp8_to_fp4 dec_a (.complex_fp8(rd_data_a_16), .complex_fp4(rd_a_fp8_as_fp4));
    complex_fp8_to_fp4 dec_b (.complex_fp8(rd_data_b_16), .complex_fp4(rd_b_fp8_as_fp4));

    wire [15:0] rd_a_fp4_as_fp8, rd_b_fp4_as_fp8;
    complex_fp4_to_fp8 enc_a (.complex_fp4(rd_data_a_16[7:0]), .complex_fp8(rd_a_fp4_as_fp8));
    complex_fp4_to_fp8 enc_b (.complex_fp4(rd_data_b_16[7:0]), .complex_fp8(rd_b_fp4_as_fp8));

    wire [23:0] mem_rd_a_24 = cur_rd_prec ? {rd_data_a_16, rd_a_fp8_as_fp4} : {rd_a_fp4_as_fp8, rd_data_a_16[7:0]};
    wire [23:0] mem_rd_b_24 = cur_rd_prec ? {rd_data_b_16, rd_b_fp8_as_fp4} : {rd_b_fp4_as_fp8, rd_data_b_16[7:0]};

    // Read matching line registers (BRAM Read Latency 2 -> CORDIC Execution 11 = 9 Cycle Shift Needed)
    reg [23:0] A_24_pipe [0:8];
    reg [23:0] B_24_pipe [0:8];
    always @(posedge clk) begin
        A_24_pipe[0] <= mem_rd_a_24;
        B_24_pipe[0] <= mem_rd_b_24;
        for (integer j = 1; j < 9; j = j + 1) begin
            A_24_pipe[j] <= A_24_pipe[j-1];
            B_24_pipe[j] <= B_24_pipe[j-1];
        end
    end
    wire [23:0] A_24_aligned = A_24_pipe[8];
    wire [23:0] B_24_aligned = B_24_pipe[8];
    // Per-stage butterfly wrappers matrix matrix
    wire [15:0] X_st0, Y_st0;
    wire        fp8_out_st0;
    wire [15:0] X_st1, Y_st1;
    wire        fp8_out_st1;
    wire [15:0] X_st2, Y_st2;
    wire        fp8_out_st2;
    wire [15:0] X_st3, Y_st3;
    wire        fp8_out_st3;
    wire [15:0] X_st4, Y_st4;
    wire        fp8_out_st4;
    wire [15:0] X_st5, Y_st5;
    wire        fp8_out_st5;
    wire [15:0] X_st6, Y_st6;
    wire        fp8_out_st6;
    wire [15:0] X_st7, Y_st7;
    wire        fp8_out_st7;
    wire [15:0] X_st8, Y_st8;
    wire        fp8_out_st8;
    wire [15:0] X_st9, Y_st9;
    wire        fp8_out_st9;

    butterfly_wrapper #(
        .MULT_PRECISION(0),
        .ADD_PRECISION (0)
    ) bf_st0 (
        .A            (A_24_aligned),
        .B            (B_24_aligned),
        .W            (twiddle),
        .X            (X_st0),
        .Y            (Y_st0),
        .output_is_fp8(fp8_out_st0)
    );

    butterfly_wrapper #(
        .MULT_PRECISION(0),
        .ADD_PRECISION (0)
    ) bf_st1 (
        .A            (A_24_aligned),
        .B            (B_24_aligned),
        .W            (twiddle),
        .X            (X_st1),
        .Y            (Y_st1),
        .output_is_fp8(fp8_out_st1)
    );

    butterfly_wrapper #(
        .MULT_PRECISION(0),
        .ADD_PRECISION (0)
    ) bf_st2 (
        .A            (A_24_aligned),
        .B            (B_24_aligned),
        .W            (twiddle),
        .X            (X_st2),
        .Y            (Y_st2),
        .output_is_fp8(fp8_out_st2)
    );

    butterfly_wrapper #(
        .MULT_PRECISION(0),
        .ADD_PRECISION (0)
    ) bf_st3 (
        .A            (A_24_aligned),
        .B            (B_24_aligned),
        .W            (twiddle),
        .X            (X_st3),
        .Y            (Y_st3),
        .output_is_fp8(fp8_out_st3)
    );

    butterfly_wrapper #(
        .MULT_PRECISION(1),
        .ADD_PRECISION (0)
    ) bf_st4 (
        .A            (A_24_aligned),
        .B            (B_24_aligned),
        .W            (twiddle),
        .X            (X_st4),
        .Y            (Y_st4),
        .output_is_fp8(fp8_out_st4)
    );

    butterfly_wrapper #(
        .MULT_PRECISION(0),
        .ADD_PRECISION (0)
    ) bf_st5 (
        .A            (A_24_aligned),
        .B            (B_24_aligned),
        .W            (twiddle),
        .X            (X_st5),
        .Y            (Y_st5),
        .output_is_fp8(fp8_out_st5)
    );

    butterfly_wrapper #(
        .MULT_PRECISION(0),
        .ADD_PRECISION (0)
    ) bf_st6 (
        .A            (A_24_aligned),
        .B            (B_24_aligned),
        .W            (twiddle),
        .X            (X_st6),
        .Y            (Y_st6),
        .output_is_fp8(fp8_out_st6)
    );

    butterfly_wrapper #(
        .MULT_PRECISION(0),
        .ADD_PRECISION (0)
    ) bf_st7 (
        .A            (A_24_aligned),
        .B            (B_24_aligned),
        .W            (twiddle),
        .X            (X_st7),
        .Y            (Y_st7),
        .output_is_fp8(fp8_out_st7)
    );

    butterfly_wrapper #(
        .MULT_PRECISION(0),
        .ADD_PRECISION (0)
    ) bf_st8 (
        .A            (A_24_aligned),
        .B            (B_24_aligned),
        .W            (twiddle),
        .X            (X_st8),
        .Y            (Y_st8),
        .output_is_fp8(fp8_out_st8)
    );

    butterfly_wrapper #(
        .MULT_PRECISION(0),
        .ADD_PRECISION (0)
    ) bf_st9 (
        .A            (A_24_aligned),
        .B            (B_24_aligned),
        .W            (twiddle),
        .X            (X_st9),
        .Y            (Y_st9),
        .output_is_fp8(fp8_out_st9)
    );

    reg [15:0] X_bf, Y_bf;
    reg        bf_is_fp8;
    always @(*) begin
        case (curr_stage_delayed[3:0])
            4'd0: begin X_bf = X_st0; Y_bf = Y_st0; bf_is_fp8 = fp8_out_st0; end
            4'd1: begin X_bf = X_st1; Y_bf = Y_st1; bf_is_fp8 = fp8_out_st1; end
            4'd2: begin X_bf = X_st2; Y_bf = Y_st2; bf_is_fp8 = fp8_out_st2; end
            4'd3: begin X_bf = X_st3; Y_bf = Y_st3; bf_is_fp8 = fp8_out_st3; end
            4'd4: begin X_bf = X_st4; Y_bf = Y_st4; bf_is_fp8 = fp8_out_st4; end
            4'd5: begin X_bf = X_st5; Y_bf = Y_st5; bf_is_fp8 = fp8_out_st5; end
            4'd6: begin X_bf = X_st6; Y_bf = Y_st6; bf_is_fp8 = fp8_out_st6; end
            4'd7: begin X_bf = X_st7; Y_bf = Y_st7; bf_is_fp8 = fp8_out_st7; end
            4'd8: begin X_bf = X_st8; Y_bf = Y_st8; bf_is_fp8 = fp8_out_st8; end
            4'd9: begin X_bf = X_st9; Y_bf = Y_st9; bf_is_fp8 = fp8_out_st9; end
            default: begin X_bf = 16'h0; Y_bf = 16'h0; bf_is_fp8 = 1'b0; end
        endcase
    end
    // Stream writeback formatting matrix
    wire [7:0]  X_fp4_packed, Y_fp4_packed;
    wire [15:0] X_fp8_packed, Y_fp8_packed;

    fp8_to_fp4_converter conv_xr (.fp8_in(X_bf[15:8]), .fp4_out(X_fp4_packed[7:4]));
    fp8_to_fp4_converter conv_xi (.fp8_in(X_bf[7:0]),  .fp4_out(X_fp4_packed[3:0]));
    fp8_to_fp4_converter conv_yr (.fp8_in(Y_bf[15:8]), .fp4_out(Y_fp4_packed[7:4]));
    fp8_to_fp4_converter conv_yi (.fp8_in(Y_bf[7:0]),  .fp4_out(Y_fp4_packed[3:0]));

    fp4_to_fp8_converter conv_xr8 (.fp4_in(X_bf[7:4]), .fp8_out(X_fp8_packed[15:8]));
    fp4_to_fp8_converter conv_xi8 (.fp4_in(X_bf[3:0]), .fp8_out(X_fp8_packed[7:0]));
    fp4_to_fp8_converter conv_yr8 (.fp4_in(Y_bf[7:4]), .fp8_out(Y_fp8_packed[15:8]));
    fp4_to_fp8_converter conv_yi8 (.fp4_in(Y_bf[3:0]), .fp8_out(Y_fp8_packed[7:0]));

    wire [23:0] X_wr_24 = bf_is_fp8 ? {X_bf, X_fp4_packed} : {X_fp8_packed, X_bf[7:0]};
    wire [23:0] Y_wr_24 = bf_is_fp8 ? {Y_bf, Y_fp4_packed} : {Y_fp8_packed, Y_bf[7:0]};

    // =========================================================================
    // CONTROL PATH COUPLING FSM
    // =========================================================================
    localparam IDLE_ST   = 2'd0,
               RUN_ST    = 2'd1,
               FLUSH_ST  = 2'd2,
               DONE_ST   = 2'd3;

    reg [1:0]  state;
    reg [5:0]  flush_counter;

    always @(posedge clk or negedge rst) begin
        if (!rst) begin
            state         <= IDLE_ST;
            start_agu_reg <= 1'b0;
            fft_bank_sel  <= 1'b0;
            done          <= 1'b0;
            flush_counter <= 0;
        end else begin
            case (state)
                IDLE_ST: begin
                    done <= 1'b0;
                    if (start) begin
                        fft_bank_sel  <= 1'b1;
                        start_agu_reg <= 1'b1;
                        state         <= RUN_ST;
                    end
                end

                RUN_ST: begin
                    start_agu_reg <= 1'b0;
                    if (done_stage && !done_fft) begin
                        fft_bank_sel <= ~fft_bank_sel; // Flip macro ping-pong banks on stage boundaries
                    end
                    if (done_fft) begin
                        state         <= FLUSH_ST;
                        flush_counter <= TOTAL_LATENCY;
                    end
                end

                FLUSH_ST: begin
                    if (flush_counter == 0) begin
                        fft_bank_sel <= 1'b1;
                        done         <= 1'b1;
                        state        <= DONE_ST;
                    end else begin
                        flush_counter <= flush_counter - 1;
                    end
                end

                DONE_ST: begin
                    if (!start) begin
                        done  <= 1'b0;
                        state <= IDLE_ST;
                    end
                end
                default: state <= IDLE_ST;
            endcase
        end
    end

endmodule
