// =============================================================================
// Mixed-Precision FFT TOP – 8-point PIPELINED CONFIGURATION
// Auto-generated by FFTTemplateGenerator
// =============================================================================
`timescale 1ns/1ps

module pipelined_fft_8_sweep_6_top (
    input  wire        clk,
    input  wire        rst,     

    // Control
    input  wire        start,
    output reg         done,

    // Load Interface
    input  wire              load_en,
    input  wire [2:0]  load_addr,
    input  wire [15:0]       load_data,

    // Unload Interface
    input  wire              unload_en,
    input  wire [2:0]  unload_addr,
    output wire [15:0]       unload_data
);

    wire [10:0] load_addr_rev;

    bit_reverse #(
        .MAX_N(1024),
        .WIDTH(11)
    ) br (
        .in  ({{ 8'b0, load_addr }}),
        .N   (11'd8),
        .out (load_addr_rev)
    );

    reg bank_sel;
    wire core_done;
    wire [15:0] core_rd_data;

    pipelined_fft_8_sweep_6_core #(
        .MAX_N     (1024),
        .ADDR_WIDTH(11)
    ) core (
        .clk          (clk),
        .rst          (rst),
        .start        (start),
        .done         (core_done),

        .ext_wr_en    (load_en),
        .ext_wr_addr  (load_addr_rev),
        .ext_wr_data  ({ load_data, 8'h00 }),  

        .ext_reading  (unload_en),
        .ext_rd_addr  ({{ 8'b0, unload_addr }}),
        .ext_rd_data  (core_rd_data),

        .ext_bank_sel (bank_sel)
    );

    assign unload_data = core_rd_data;

    always @(posedge clk or negedge rst) begin
        if (!rst) begin
            done     <= 1'b0;
            bank_sel <= 1'b1;
        end else begin
            if (load_en && !start)
                bank_sel <= 1'b1;

            if (start) begin
                done     <= 1'b0;
                bank_sel <= 1'b1;
            end else if (core_done) begin
                done     <= 1'b1;
                bank_sel <= 1'b0;
            end else if (!start && done) begin
                done <= 1'b0;
            end
        end
    end

endmodule
