// =============================================================================
// FP32 Twiddle Factor ROM -- synthesizable case-statement version
// =============================================================================
// AUTO-GENERATED by generate_fp32_twiddles.py -- do not hand-edit the ROM
// table below; re-run the generator instead.
//
// Mirrors twiddle_factor_unified in verilog_sources/twiddle_rom_synthesizable.v:
// same dynamic k-scaling for runtime N, same half-plane symmetry +
// conjugation, same hardcoded -1.0 midpoint. The stored word is 64-bit
// complex FP32 instead of the 24-bit unified FP8+FP4 word, and there is no
// PRECISION port.
//
// ROM word format: [63:32] FP32 Real, [31:0] FP32 Imag
//
// FIX (synthesis): replaced the $readmemb-based memory with a fully
// synthesizable registered-case ROM. All 512 entries are sourced
// directly from twiddles_fp32_1024.txt (authoritative) via
// generate_fp32_twiddles.py. Yosys/OpenROAD infer this as a ROM mapped to
// library cells -- no external file dependency at synthesis time, no
// working-directory-relative path to get wrong.
//
// Conjugate symmetry: only k=0..511 are stored.
//   W_N^{N-k} = conj(W_N^k) -> second half handled by flipping the
//   imaginary sign bit. k=512 (W=-1+0j) is hardcoded separately.
// =============================================================================

module twiddle_factor_fp32 #(
    parameter MAX_N      = 1024,
    parameter ADDR_WIDTH = $clog2(MAX_N) + 1
)(
    input  [ADDR_WIDTH-1:0] k,            // Index k
    input  [ADDR_WIDTH-1:0] n,            // Current FFT size N
    output reg [63:0]       twiddle_out
);

    // --------------------------------------------------------
    // 1. Dynamic Scaling Logic
    // --------------------------------------------------------
    reg [ADDR_WIDTH-1:0] scaled_k;

    always @(*) begin
        case (n)
            1024: scaled_k = k;
            512:  scaled_k = {k, 1'b0};         // k * 2
            256:  scaled_k = {k, 2'b00};        // k * 4
            128:  scaled_k = {k, 3'b000};       // k * 8
            64:   scaled_k = {k, 4'b0000};      // k * 16
            32:   scaled_k = {k, 5'b00000};     // k * 32
            16:   scaled_k = {k, 6'b000000};    // k * 64
            8:    scaled_k = {k, 7'b0000000};   // k * 128
            4:    scaled_k = {k, 8'b00000000};  // k * 256
            2:    scaled_k = {k, 9'b000000000}; // k * 512
            default: scaled_k = 11'd0;
        endcase
    end

    // --------------------------------------------------------
    // 2. Symmetry Logic
    // --------------------------------------------------------
    reg        use_conjugate;
    reg [9:0]  rom_addr;       // Address within the 0-511 block
    reg        is_midpoint;

    always @(*) begin
        is_midpoint = 1'b0;

        if (scaled_k == 512) begin
            // 180 degrees is a boundary case
            is_midpoint   = 1'b1;
            rom_addr      = 0;
            use_conjugate = 1'b0;
        end
        else if (scaled_k > 511) begin
            // Second half (180 < angle < 360) -> Symmetry
            rom_addr      = 1024 - scaled_k;
            use_conjugate = 1'b1;
        end
        else begin
            // First half (0 <= angle < 180)
            rom_addr      = scaled_k;
            use_conjugate = 1'b0;
        end
    end

    // --------------------------------------------------------
    // 3. ROM -- 512 entries, combinational case statement.
    //    Yosys/synthesis infers this as a ROM, not flip-flops.
    // --------------------------------------------------------
    reg [63:0] raw_data;

    always @(*) begin
        case (rom_addr)
            10'd0: raw_data = 64'h3F80000000000000;
            10'd1: raw_data = 64'h3F7FFEC4BBC90F88;
            10'd2: raw_data = 64'h3F7FFB11BC490E90;
            10'd3: raw_data = 64'h3F7FF4E6BC96C9B6;
            10'd4: raw_data = 64'h3F7FEC43BCC90AB0;
            10'd5: raw_data = 64'h3F7FE129BCFB49BA;
            10'd6: raw_data = 64'h3F7FD397BD16C32C;
            10'd7: raw_data = 64'h3F7FC38FBD2FE007;
            10'd8: raw_data = 64'h3F7FB10FBD48FB30;
            10'd9: raw_data = 64'h3F7F9C18BD621469;
            10'd10: raw_data = 64'h3F7F84ABBD7B2B74;
            10'd11: raw_data = 64'h3F7F6AC7BD8A200A;
            10'd12: raw_data = 64'h3F7F4E6DBD96A905;
            10'd13: raw_data = 64'h3F7F2F9DBDA3308C;
            10'd14: raw_data = 64'h3F7F0E58BDAFB680;
            10'd15: raw_data = 64'h3F7EEA9DBDBC3AC3;
            10'd16: raw_data = 64'h3F7EC46DBDC8BD36;
            10'd17: raw_data = 64'h3F7E9BC9BDD53DB9;
            10'd18: raw_data = 64'h3F7E70B0BDE1BC2E;
            10'd19: raw_data = 64'h3F7E4323BDEE3876;
            10'd20: raw_data = 64'h3F7E1324BDFAB273;
            10'd21: raw_data = 64'h3F7DE0B1BE039502;
            10'd22: raw_data = 64'h3F7DABCCBE09CF86;
            10'd23: raw_data = 64'h3F7D7474BE1008B7;
            10'd24: raw_data = 64'h3F7D3AACBE164083;
            10'd25: raw_data = 64'h3F7CFE73BE1C76DE;
            10'd26: raw_data = 64'h3F7CBFC9BE22ABB6;
            10'd27: raw_data = 64'h3F7C7EB0BE28DEFC;
            10'd28: raw_data = 64'h3F7C3B28BE2F10A2;
            10'd29: raw_data = 64'h3F7BF531BE354098;
            10'd30: raw_data = 64'h3F7BACCDBE3B6ECF;
            10'd31: raw_data = 64'h3F7B61FCBE419B37;
            10'd32: raw_data = 64'h3F7B14BEBE47C5C2;
            10'd33: raw_data = 64'h3F7AC516BE4DEE60;
            10'd34: raw_data = 64'h3F7A7302BE541501;
            10'd35: raw_data = 64'h3F7A1E84BE5A3997;
            10'd36: raw_data = 64'h3F79C79DBE605C13;
            10'd37: raw_data = 64'h3F796E4EBE667C66;
            10'd38: raw_data = 64'h3F791298BE6C9A7F;
            10'd39: raw_data = 64'h3F78B47BBE72B651;
            10'd40: raw_data = 64'h3F7853F8BE78CFCC;
            10'd41: raw_data = 64'h3F77F110BE7EE6E1;
            10'd42: raw_data = 64'h3F778BC5BE827DC0;
            10'd43: raw_data = 64'h3F772417BE8586CE;
            10'd44: raw_data = 64'h3F76BA07BE888E93;
            10'd45: raw_data = 64'h3F764D97BE8B9507;
            10'd46: raw_data = 64'h3F75DEC6BE8E9A22;
            10'd47: raw_data = 64'h3F756D97BE919DDD;
            10'd48: raw_data = 64'h3F74FA0BBE94A031;
            10'd49: raw_data = 64'h3F748422BE97A117;
            10'd50: raw_data = 64'h3F740BDDBE9AA086;
            10'd51: raw_data = 64'h3F73913FBE9D9E78;
            10'd52: raw_data = 64'h3F731447BEA09AE5;
            10'd53: raw_data = 64'h3F7294F8BEA395C5;
            10'd54: raw_data = 64'h3F721352BEA68F12;
            10'd55: raw_data = 64'h3F718F57BEA986C4;
            10'd56: raw_data = 64'h3F710908BEAC7CD4;
            10'd57: raw_data = 64'h3F708066BEAF713A;
            10'd58: raw_data = 64'h3F6FF573BEB263EF;
            10'd59: raw_data = 64'h3F6F6830BEB554EC;
            10'd60: raw_data = 64'h3F6ED89EBEB8442A;
            10'd61: raw_data = 64'h3F6E46BEBEBB31A0;
            10'd62: raw_data = 64'h3F6DB293BEBE1D4A;
            10'd63: raw_data = 64'h3F6D1C1DBEC1071E;
            10'd64: raw_data = 64'h3F6C835EBEC3EF15;
            10'd65: raw_data = 64'h3F6BE858BEC6D529;
            10'd66: raw_data = 64'h3F6B4B0CBEC9B953;
            10'd67: raw_data = 64'h3F6AAB7BBECC9B8B;
            10'd68: raw_data = 64'h3F6A09A7BECF7BCA;
            10'd69: raw_data = 64'h3F696591BED25A09;
            10'd70: raw_data = 64'h3F68BF3CBED53641;
            10'd71: raw_data = 64'h3F6816A8BED8106B;
            10'd72: raw_data = 64'h3F676BD8BEDAE880;
            10'd73: raw_data = 64'h3F66BECCBEDDBE79;
            10'd74: raw_data = 64'h3F660F88BEE0924F;
            10'd75: raw_data = 64'h3F655E0BBEE363FA;
            10'd76: raw_data = 64'h3F64AA59BEE63375;
            10'd77: raw_data = 64'h3F63F473BEE900B7;
            10'd78: raw_data = 64'h3F633C5ABEEBCBBB;
            10'd79: raw_data = 64'h3F628210BEEE9479;
            10'd80: raw_data = 64'h3F61C598BEF15AEA;
            10'd81: raw_data = 64'h3F6106F2BEF41F07;
            10'd82: raw_data = 64'h3F604621BEF6E0CB;
            10'd83: raw_data = 64'h3F5F8327BEF9A02D;
            10'd84: raw_data = 64'h3F5EBE05BEFC5D27;
            10'd85: raw_data = 64'h3F5DF6BEBEFF17B2;
            10'd86: raw_data = 64'h3F5D2D53BF00E7E4;
            10'd87: raw_data = 64'h3F5C61C7BF0242B1;
            10'd88: raw_data = 64'h3F5B941ABF039C3D;
            10'd89: raw_data = 64'h3F5AC450BF04F484;
            10'd90: raw_data = 64'h3F59F26ABF064B82;
            10'd91: raw_data = 64'h3F591E6ABF07A136;
            10'd92: raw_data = 64'h3F584853BF08F59B;
            10'd93: raw_data = 64'h3F577026BF0A48AD;
            10'd94: raw_data = 64'h3F5695E5BF0B9A6B;
            10'd95: raw_data = 64'h3F55B993BF0CEAD0;
            10'd96: raw_data = 64'h3F54DB31BF0E39DA;
            10'd97: raw_data = 64'h3F53FAC3BF0F8784;
            10'd98: raw_data = 64'h3F531849BF10D3CD;
            10'd99: raw_data = 64'h3F5233C6BF121EB0;
            10'd100: raw_data = 64'h3F514D3DBF13682A;
            10'd101: raw_data = 64'h3F5064AFBF14B039;
            10'd102: raw_data = 64'h3F4F7A1FBF15F6D9;
            10'd103: raw_data = 64'h3F4E8D90BF173C07;
            10'd104: raw_data = 64'h3F4D9F02BF187FC0;
            10'd105: raw_data = 64'h3F4CAE79BF19C200;
            10'd106: raw_data = 64'h3F4BBBF8BF1B02C6;
            10'd107: raw_data = 64'h3F4AC77FBF1C420C;
            10'd108: raw_data = 64'h3F49D112BF1D7FD1;
            10'd109: raw_data = 64'h3F48D8B3BF1EBC12;
            10'd110: raw_data = 64'h3F47DE65BF1FF6CB;
            10'd111: raw_data = 64'h3F46E22ABF212FF9;
            10'd112: raw_data = 64'h3F45E403BF226799;
            10'd113: raw_data = 64'h3F44E3F5BF239DA9;
            10'd114: raw_data = 64'h3F43E200BF24D225;
            10'd115: raw_data = 64'h3F42DE29BF26050A;
            10'd116: raw_data = 64'h3F41D870BF273656;
            10'd117: raw_data = 64'h3F40D0DABF286605;
            10'd118: raw_data = 64'h3F3FC767BF299415;
            10'd119: raw_data = 64'h3F3EBC1BBF2AC082;
            10'd120: raw_data = 64'h3F3DAEF9BF2BEB4A;
            10'd121: raw_data = 64'h3F3CA003BF2D1469;
            10'd122: raw_data = 64'h3F3B8F3BBF2E3BDE;
            10'd123: raw_data = 64'h3F3A7CA4BF2F61A5;
            10'd124: raw_data = 64'h3F396842BF3085BB;
            10'd125: raw_data = 64'h3F385216BF31A81D;
            10'd126: raw_data = 64'h3F373A23BF32C8C9;
            10'd127: raw_data = 64'h3F36206CBF33E7BC;
            10'd128: raw_data = 64'h3F3504F3BF3504F3;
            10'd129: raw_data = 64'h3F33E7BCBF36206C;
            10'd130: raw_data = 64'h3F32C8C9BF373A23;
            10'd131: raw_data = 64'h3F31A81DBF385216;
            10'd132: raw_data = 64'h3F3085BBBF396842;
            10'd133: raw_data = 64'h3F2F61A5BF3A7CA4;
            10'd134: raw_data = 64'h3F2E3BDEBF3B8F3B;
            10'd135: raw_data = 64'h3F2D1469BF3CA003;
            10'd136: raw_data = 64'h3F2BEB4ABF3DAEF9;
            10'd137: raw_data = 64'h3F2AC082BF3EBC1B;
            10'd138: raw_data = 64'h3F299415BF3FC767;
            10'd139: raw_data = 64'h3F286605BF40D0DA;
            10'd140: raw_data = 64'h3F273656BF41D870;
            10'd141: raw_data = 64'h3F26050ABF42DE29;
            10'd142: raw_data = 64'h3F24D225BF43E200;
            10'd143: raw_data = 64'h3F239DA9BF44E3F5;
            10'd144: raw_data = 64'h3F226799BF45E403;
            10'd145: raw_data = 64'h3F212FF9BF46E22A;
            10'd146: raw_data = 64'h3F1FF6CBBF47DE65;
            10'd147: raw_data = 64'h3F1EBC12BF48D8B3;
            10'd148: raw_data = 64'h3F1D7FD1BF49D112;
            10'd149: raw_data = 64'h3F1C420CBF4AC77F;
            10'd150: raw_data = 64'h3F1B02C6BF4BBBF8;
            10'd151: raw_data = 64'h3F19C200BF4CAE79;
            10'd152: raw_data = 64'h3F187FC0BF4D9F02;
            10'd153: raw_data = 64'h3F173C07BF4E8D90;
            10'd154: raw_data = 64'h3F15F6D9BF4F7A1F;
            10'd155: raw_data = 64'h3F14B039BF5064AF;
            10'd156: raw_data = 64'h3F13682ABF514D3D;
            10'd157: raw_data = 64'h3F121EB0BF5233C6;
            10'd158: raw_data = 64'h3F10D3CDBF531849;
            10'd159: raw_data = 64'h3F0F8784BF53FAC3;
            10'd160: raw_data = 64'h3F0E39DABF54DB31;
            10'd161: raw_data = 64'h3F0CEAD0BF55B993;
            10'd162: raw_data = 64'h3F0B9A6BBF5695E5;
            10'd163: raw_data = 64'h3F0A48ADBF577026;
            10'd164: raw_data = 64'h3F08F59BBF584853;
            10'd165: raw_data = 64'h3F07A136BF591E6A;
            10'd166: raw_data = 64'h3F064B82BF59F26A;
            10'd167: raw_data = 64'h3F04F484BF5AC450;
            10'd168: raw_data = 64'h3F039C3DBF5B941A;
            10'd169: raw_data = 64'h3F0242B1BF5C61C7;
            10'd170: raw_data = 64'h3F00E7E4BF5D2D53;
            10'd171: raw_data = 64'h3EFF17B2BF5DF6BE;
            10'd172: raw_data = 64'h3EFC5D27BF5EBE05;
            10'd173: raw_data = 64'h3EF9A02DBF5F8327;
            10'd174: raw_data = 64'h3EF6E0CBBF604621;
            10'd175: raw_data = 64'h3EF41F07BF6106F2;
            10'd176: raw_data = 64'h3EF15AEABF61C598;
            10'd177: raw_data = 64'h3EEE9479BF628210;
            10'd178: raw_data = 64'h3EEBCBBBBF633C5A;
            10'd179: raw_data = 64'h3EE900B7BF63F473;
            10'd180: raw_data = 64'h3EE63375BF64AA59;
            10'd181: raw_data = 64'h3EE363FABF655E0B;
            10'd182: raw_data = 64'h3EE0924FBF660F88;
            10'd183: raw_data = 64'h3EDDBE79BF66BECC;
            10'd184: raw_data = 64'h3EDAE880BF676BD8;
            10'd185: raw_data = 64'h3ED8106BBF6816A8;
            10'd186: raw_data = 64'h3ED53641BF68BF3C;
            10'd187: raw_data = 64'h3ED25A09BF696591;
            10'd188: raw_data = 64'h3ECF7BCABF6A09A7;
            10'd189: raw_data = 64'h3ECC9B8BBF6AAB7B;
            10'd190: raw_data = 64'h3EC9B953BF6B4B0C;
            10'd191: raw_data = 64'h3EC6D529BF6BE858;
            10'd192: raw_data = 64'h3EC3EF15BF6C835E;
            10'd193: raw_data = 64'h3EC1071EBF6D1C1D;
            10'd194: raw_data = 64'h3EBE1D4ABF6DB293;
            10'd195: raw_data = 64'h3EBB31A0BF6E46BE;
            10'd196: raw_data = 64'h3EB8442ABF6ED89E;
            10'd197: raw_data = 64'h3EB554ECBF6F6830;
            10'd198: raw_data = 64'h3EB263EFBF6FF573;
            10'd199: raw_data = 64'h3EAF713ABF708066;
            10'd200: raw_data = 64'h3EAC7CD4BF710908;
            10'd201: raw_data = 64'h3EA986C4BF718F57;
            10'd202: raw_data = 64'h3EA68F12BF721352;
            10'd203: raw_data = 64'h3EA395C5BF7294F8;
            10'd204: raw_data = 64'h3EA09AE5BF731447;
            10'd205: raw_data = 64'h3E9D9E78BF73913F;
            10'd206: raw_data = 64'h3E9AA086BF740BDD;
            10'd207: raw_data = 64'h3E97A117BF748422;
            10'd208: raw_data = 64'h3E94A031BF74FA0B;
            10'd209: raw_data = 64'h3E919DDDBF756D97;
            10'd210: raw_data = 64'h3E8E9A22BF75DEC6;
            10'd211: raw_data = 64'h3E8B9507BF764D97;
            10'd212: raw_data = 64'h3E888E93BF76BA07;
            10'd213: raw_data = 64'h3E8586CEBF772417;
            10'd214: raw_data = 64'h3E827DC0BF778BC5;
            10'd215: raw_data = 64'h3E7EE6E1BF77F110;
            10'd216: raw_data = 64'h3E78CFCCBF7853F8;
            10'd217: raw_data = 64'h3E72B651BF78B47B;
            10'd218: raw_data = 64'h3E6C9A7FBF791298;
            10'd219: raw_data = 64'h3E667C66BF796E4E;
            10'd220: raw_data = 64'h3E605C13BF79C79D;
            10'd221: raw_data = 64'h3E5A3997BF7A1E84;
            10'd222: raw_data = 64'h3E541501BF7A7302;
            10'd223: raw_data = 64'h3E4DEE60BF7AC516;
            10'd224: raw_data = 64'h3E47C5C2BF7B14BE;
            10'd225: raw_data = 64'h3E419B37BF7B61FC;
            10'd226: raw_data = 64'h3E3B6ECFBF7BACCD;
            10'd227: raw_data = 64'h3E354098BF7BF531;
            10'd228: raw_data = 64'h3E2F10A2BF7C3B28;
            10'd229: raw_data = 64'h3E28DEFCBF7C7EB0;
            10'd230: raw_data = 64'h3E22ABB6BF7CBFC9;
            10'd231: raw_data = 64'h3E1C76DEBF7CFE73;
            10'd232: raw_data = 64'h3E164083BF7D3AAC;
            10'd233: raw_data = 64'h3E1008B7BF7D7474;
            10'd234: raw_data = 64'h3E09CF86BF7DABCC;
            10'd235: raw_data = 64'h3E039502BF7DE0B1;
            10'd236: raw_data = 64'h3DFAB273BF7E1324;
            10'd237: raw_data = 64'h3DEE3876BF7E4323;
            10'd238: raw_data = 64'h3DE1BC2EBF7E70B0;
            10'd239: raw_data = 64'h3DD53DB9BF7E9BC9;
            10'd240: raw_data = 64'h3DC8BD36BF7EC46D;
            10'd241: raw_data = 64'h3DBC3AC3BF7EEA9D;
            10'd242: raw_data = 64'h3DAFB680BF7F0E58;
            10'd243: raw_data = 64'h3DA3308CBF7F2F9D;
            10'd244: raw_data = 64'h3D96A905BF7F4E6D;
            10'd245: raw_data = 64'h3D8A200ABF7F6AC7;
            10'd246: raw_data = 64'h3D7B2B74BF7F84AB;
            10'd247: raw_data = 64'h3D621469BF7F9C18;
            10'd248: raw_data = 64'h3D48FB30BF7FB10F;
            10'd249: raw_data = 64'h3D2FE007BF7FC38F;
            10'd250: raw_data = 64'h3D16C32CBF7FD397;
            10'd251: raw_data = 64'h3CFB49BABF7FE129;
            10'd252: raw_data = 64'h3CC90AB0BF7FEC43;
            10'd253: raw_data = 64'h3C96C9B6BF7FF4E6;
            10'd254: raw_data = 64'h3C490E90BF7FFB11;
            10'd255: raw_data = 64'h3BC90F88BF7FFEC4;
            10'd256: raw_data = 64'h248D3132BF800000;
            10'd257: raw_data = 64'hBBC90F88BF7FFEC4;
            10'd258: raw_data = 64'hBC490E90BF7FFB11;
            10'd259: raw_data = 64'hBC96C9B6BF7FF4E6;
            10'd260: raw_data = 64'hBCC90AB0BF7FEC43;
            10'd261: raw_data = 64'hBCFB49BABF7FE129;
            10'd262: raw_data = 64'hBD16C32CBF7FD397;
            10'd263: raw_data = 64'hBD2FE007BF7FC38F;
            10'd264: raw_data = 64'hBD48FB30BF7FB10F;
            10'd265: raw_data = 64'hBD621469BF7F9C18;
            10'd266: raw_data = 64'hBD7B2B74BF7F84AB;
            10'd267: raw_data = 64'hBD8A200ABF7F6AC7;
            10'd268: raw_data = 64'hBD96A905BF7F4E6D;
            10'd269: raw_data = 64'hBDA3308CBF7F2F9D;
            10'd270: raw_data = 64'hBDAFB680BF7F0E58;
            10'd271: raw_data = 64'hBDBC3AC3BF7EEA9D;
            10'd272: raw_data = 64'hBDC8BD36BF7EC46D;
            10'd273: raw_data = 64'hBDD53DB9BF7E9BC9;
            10'd274: raw_data = 64'hBDE1BC2EBF7E70B0;
            10'd275: raw_data = 64'hBDEE3876BF7E4323;
            10'd276: raw_data = 64'hBDFAB273BF7E1324;
            10'd277: raw_data = 64'hBE039502BF7DE0B1;
            10'd278: raw_data = 64'hBE09CF86BF7DABCC;
            10'd279: raw_data = 64'hBE1008B7BF7D7474;
            10'd280: raw_data = 64'hBE164083BF7D3AAC;
            10'd281: raw_data = 64'hBE1C76DEBF7CFE73;
            10'd282: raw_data = 64'hBE22ABB6BF7CBFC9;
            10'd283: raw_data = 64'hBE28DEFCBF7C7EB0;
            10'd284: raw_data = 64'hBE2F10A2BF7C3B28;
            10'd285: raw_data = 64'hBE354098BF7BF531;
            10'd286: raw_data = 64'hBE3B6ECFBF7BACCD;
            10'd287: raw_data = 64'hBE419B37BF7B61FC;
            10'd288: raw_data = 64'hBE47C5C2BF7B14BE;
            10'd289: raw_data = 64'hBE4DEE60BF7AC516;
            10'd290: raw_data = 64'hBE541501BF7A7302;
            10'd291: raw_data = 64'hBE5A3997BF7A1E84;
            10'd292: raw_data = 64'hBE605C13BF79C79D;
            10'd293: raw_data = 64'hBE667C66BF796E4E;
            10'd294: raw_data = 64'hBE6C9A7FBF791298;
            10'd295: raw_data = 64'hBE72B651BF78B47B;
            10'd296: raw_data = 64'hBE78CFCCBF7853F8;
            10'd297: raw_data = 64'hBE7EE6E1BF77F110;
            10'd298: raw_data = 64'hBE827DC0BF778BC5;
            10'd299: raw_data = 64'hBE8586CEBF772417;
            10'd300: raw_data = 64'hBE888E93BF76BA07;
            10'd301: raw_data = 64'hBE8B9507BF764D97;
            10'd302: raw_data = 64'hBE8E9A22BF75DEC6;
            10'd303: raw_data = 64'hBE919DDDBF756D97;
            10'd304: raw_data = 64'hBE94A031BF74FA0B;
            10'd305: raw_data = 64'hBE97A117BF748422;
            10'd306: raw_data = 64'hBE9AA086BF740BDD;
            10'd307: raw_data = 64'hBE9D9E78BF73913F;
            10'd308: raw_data = 64'hBEA09AE5BF731447;
            10'd309: raw_data = 64'hBEA395C5BF7294F8;
            10'd310: raw_data = 64'hBEA68F12BF721352;
            10'd311: raw_data = 64'hBEA986C4BF718F57;
            10'd312: raw_data = 64'hBEAC7CD4BF710908;
            10'd313: raw_data = 64'hBEAF713ABF708066;
            10'd314: raw_data = 64'hBEB263EFBF6FF573;
            10'd315: raw_data = 64'hBEB554ECBF6F6830;
            10'd316: raw_data = 64'hBEB8442ABF6ED89E;
            10'd317: raw_data = 64'hBEBB31A0BF6E46BE;
            10'd318: raw_data = 64'hBEBE1D4ABF6DB293;
            10'd319: raw_data = 64'hBEC1071EBF6D1C1D;
            10'd320: raw_data = 64'hBEC3EF15BF6C835E;
            10'd321: raw_data = 64'hBEC6D529BF6BE858;
            10'd322: raw_data = 64'hBEC9B953BF6B4B0C;
            10'd323: raw_data = 64'hBECC9B8BBF6AAB7B;
            10'd324: raw_data = 64'hBECF7BCABF6A09A7;
            10'd325: raw_data = 64'hBED25A09BF696591;
            10'd326: raw_data = 64'hBED53641BF68BF3C;
            10'd327: raw_data = 64'hBED8106BBF6816A8;
            10'd328: raw_data = 64'hBEDAE880BF676BD8;
            10'd329: raw_data = 64'hBEDDBE79BF66BECC;
            10'd330: raw_data = 64'hBEE0924FBF660F88;
            10'd331: raw_data = 64'hBEE363FABF655E0B;
            10'd332: raw_data = 64'hBEE63375BF64AA59;
            10'd333: raw_data = 64'hBEE900B7BF63F473;
            10'd334: raw_data = 64'hBEEBCBBBBF633C5A;
            10'd335: raw_data = 64'hBEEE9479BF628210;
            10'd336: raw_data = 64'hBEF15AEABF61C598;
            10'd337: raw_data = 64'hBEF41F07BF6106F2;
            10'd338: raw_data = 64'hBEF6E0CBBF604621;
            10'd339: raw_data = 64'hBEF9A02DBF5F8327;
            10'd340: raw_data = 64'hBEFC5D27BF5EBE05;
            10'd341: raw_data = 64'hBEFF17B2BF5DF6BE;
            10'd342: raw_data = 64'hBF00E7E4BF5D2D53;
            10'd343: raw_data = 64'hBF0242B1BF5C61C7;
            10'd344: raw_data = 64'hBF039C3DBF5B941A;
            10'd345: raw_data = 64'hBF04F484BF5AC450;
            10'd346: raw_data = 64'hBF064B82BF59F26A;
            10'd347: raw_data = 64'hBF07A136BF591E6A;
            10'd348: raw_data = 64'hBF08F59BBF584853;
            10'd349: raw_data = 64'hBF0A48ADBF577026;
            10'd350: raw_data = 64'hBF0B9A6BBF5695E5;
            10'd351: raw_data = 64'hBF0CEAD0BF55B993;
            10'd352: raw_data = 64'hBF0E39DABF54DB31;
            10'd353: raw_data = 64'hBF0F8784BF53FAC3;
            10'd354: raw_data = 64'hBF10D3CDBF531849;
            10'd355: raw_data = 64'hBF121EB0BF5233C6;
            10'd356: raw_data = 64'hBF13682ABF514D3D;
            10'd357: raw_data = 64'hBF14B039BF5064AF;
            10'd358: raw_data = 64'hBF15F6D9BF4F7A1F;
            10'd359: raw_data = 64'hBF173C07BF4E8D90;
            10'd360: raw_data = 64'hBF187FC0BF4D9F02;
            10'd361: raw_data = 64'hBF19C200BF4CAE79;
            10'd362: raw_data = 64'hBF1B02C6BF4BBBF8;
            10'd363: raw_data = 64'hBF1C420CBF4AC77F;
            10'd364: raw_data = 64'hBF1D7FD1BF49D112;
            10'd365: raw_data = 64'hBF1EBC12BF48D8B3;
            10'd366: raw_data = 64'hBF1FF6CBBF47DE65;
            10'd367: raw_data = 64'hBF212FF9BF46E22A;
            10'd368: raw_data = 64'hBF226799BF45E403;
            10'd369: raw_data = 64'hBF239DA9BF44E3F5;
            10'd370: raw_data = 64'hBF24D225BF43E200;
            10'd371: raw_data = 64'hBF26050ABF42DE29;
            10'd372: raw_data = 64'hBF273656BF41D870;
            10'd373: raw_data = 64'hBF286605BF40D0DA;
            10'd374: raw_data = 64'hBF299415BF3FC767;
            10'd375: raw_data = 64'hBF2AC082BF3EBC1B;
            10'd376: raw_data = 64'hBF2BEB4ABF3DAEF9;
            10'd377: raw_data = 64'hBF2D1469BF3CA003;
            10'd378: raw_data = 64'hBF2E3BDEBF3B8F3B;
            10'd379: raw_data = 64'hBF2F61A5BF3A7CA4;
            10'd380: raw_data = 64'hBF3085BBBF396842;
            10'd381: raw_data = 64'hBF31A81DBF385216;
            10'd382: raw_data = 64'hBF32C8C9BF373A23;
            10'd383: raw_data = 64'hBF33E7BCBF36206C;
            10'd384: raw_data = 64'hBF3504F3BF3504F3;
            10'd385: raw_data = 64'hBF36206CBF33E7BC;
            10'd386: raw_data = 64'hBF373A23BF32C8C9;
            10'd387: raw_data = 64'hBF385216BF31A81D;
            10'd388: raw_data = 64'hBF396842BF3085BB;
            10'd389: raw_data = 64'hBF3A7CA4BF2F61A5;
            10'd390: raw_data = 64'hBF3B8F3BBF2E3BDE;
            10'd391: raw_data = 64'hBF3CA003BF2D1469;
            10'd392: raw_data = 64'hBF3DAEF9BF2BEB4A;
            10'd393: raw_data = 64'hBF3EBC1BBF2AC082;
            10'd394: raw_data = 64'hBF3FC767BF299415;
            10'd395: raw_data = 64'hBF40D0DABF286605;
            10'd396: raw_data = 64'hBF41D870BF273656;
            10'd397: raw_data = 64'hBF42DE29BF26050A;
            10'd398: raw_data = 64'hBF43E200BF24D225;
            10'd399: raw_data = 64'hBF44E3F5BF239DA9;
            10'd400: raw_data = 64'hBF45E403BF226799;
            10'd401: raw_data = 64'hBF46E22ABF212FF9;
            10'd402: raw_data = 64'hBF47DE65BF1FF6CB;
            10'd403: raw_data = 64'hBF48D8B3BF1EBC12;
            10'd404: raw_data = 64'hBF49D112BF1D7FD1;
            10'd405: raw_data = 64'hBF4AC77FBF1C420C;
            10'd406: raw_data = 64'hBF4BBBF8BF1B02C6;
            10'd407: raw_data = 64'hBF4CAE79BF19C200;
            10'd408: raw_data = 64'hBF4D9F02BF187FC0;
            10'd409: raw_data = 64'hBF4E8D90BF173C07;
            10'd410: raw_data = 64'hBF4F7A1FBF15F6D9;
            10'd411: raw_data = 64'hBF5064AFBF14B039;
            10'd412: raw_data = 64'hBF514D3DBF13682A;
            10'd413: raw_data = 64'hBF5233C6BF121EB0;
            10'd414: raw_data = 64'hBF531849BF10D3CD;
            10'd415: raw_data = 64'hBF53FAC3BF0F8784;
            10'd416: raw_data = 64'hBF54DB31BF0E39DA;
            10'd417: raw_data = 64'hBF55B993BF0CEAD0;
            10'd418: raw_data = 64'hBF5695E5BF0B9A6B;
            10'd419: raw_data = 64'hBF577026BF0A48AD;
            10'd420: raw_data = 64'hBF584853BF08F59B;
            10'd421: raw_data = 64'hBF591E6ABF07A136;
            10'd422: raw_data = 64'hBF59F26ABF064B82;
            10'd423: raw_data = 64'hBF5AC450BF04F484;
            10'd424: raw_data = 64'hBF5B941ABF039C3D;
            10'd425: raw_data = 64'hBF5C61C7BF0242B1;
            10'd426: raw_data = 64'hBF5D2D53BF00E7E4;
            10'd427: raw_data = 64'hBF5DF6BEBEFF17B2;
            10'd428: raw_data = 64'hBF5EBE05BEFC5D27;
            10'd429: raw_data = 64'hBF5F8327BEF9A02D;
            10'd430: raw_data = 64'hBF604621BEF6E0CB;
            10'd431: raw_data = 64'hBF6106F2BEF41F07;
            10'd432: raw_data = 64'hBF61C598BEF15AEA;
            10'd433: raw_data = 64'hBF628210BEEE9479;
            10'd434: raw_data = 64'hBF633C5ABEEBCBBB;
            10'd435: raw_data = 64'hBF63F473BEE900B7;
            10'd436: raw_data = 64'hBF64AA59BEE63375;
            10'd437: raw_data = 64'hBF655E0BBEE363FA;
            10'd438: raw_data = 64'hBF660F88BEE0924F;
            10'd439: raw_data = 64'hBF66BECCBEDDBE79;
            10'd440: raw_data = 64'hBF676BD8BEDAE880;
            10'd441: raw_data = 64'hBF6816A8BED8106B;
            10'd442: raw_data = 64'hBF68BF3CBED53641;
            10'd443: raw_data = 64'hBF696591BED25A09;
            10'd444: raw_data = 64'hBF6A09A7BECF7BCA;
            10'd445: raw_data = 64'hBF6AAB7BBECC9B8B;
            10'd446: raw_data = 64'hBF6B4B0CBEC9B953;
            10'd447: raw_data = 64'hBF6BE858BEC6D529;
            10'd448: raw_data = 64'hBF6C835EBEC3EF15;
            10'd449: raw_data = 64'hBF6D1C1DBEC1071E;
            10'd450: raw_data = 64'hBF6DB293BEBE1D4A;
            10'd451: raw_data = 64'hBF6E46BEBEBB31A0;
            10'd452: raw_data = 64'hBF6ED89EBEB8442A;
            10'd453: raw_data = 64'hBF6F6830BEB554EC;
            10'd454: raw_data = 64'hBF6FF573BEB263EF;
            10'd455: raw_data = 64'hBF708066BEAF713A;
            10'd456: raw_data = 64'hBF710908BEAC7CD4;
            10'd457: raw_data = 64'hBF718F57BEA986C4;
            10'd458: raw_data = 64'hBF721352BEA68F12;
            10'd459: raw_data = 64'hBF7294F8BEA395C5;
            10'd460: raw_data = 64'hBF731447BEA09AE5;
            10'd461: raw_data = 64'hBF73913FBE9D9E78;
            10'd462: raw_data = 64'hBF740BDDBE9AA086;
            10'd463: raw_data = 64'hBF748422BE97A117;
            10'd464: raw_data = 64'hBF74FA0BBE94A031;
            10'd465: raw_data = 64'hBF756D97BE919DDD;
            10'd466: raw_data = 64'hBF75DEC6BE8E9A22;
            10'd467: raw_data = 64'hBF764D97BE8B9507;
            10'd468: raw_data = 64'hBF76BA07BE888E93;
            10'd469: raw_data = 64'hBF772417BE8586CE;
            10'd470: raw_data = 64'hBF778BC5BE827DC0;
            10'd471: raw_data = 64'hBF77F110BE7EE6E1;
            10'd472: raw_data = 64'hBF7853F8BE78CFCC;
            10'd473: raw_data = 64'hBF78B47BBE72B651;
            10'd474: raw_data = 64'hBF791298BE6C9A7F;
            10'd475: raw_data = 64'hBF796E4EBE667C66;
            10'd476: raw_data = 64'hBF79C79DBE605C13;
            10'd477: raw_data = 64'hBF7A1E84BE5A3997;
            10'd478: raw_data = 64'hBF7A7302BE541501;
            10'd479: raw_data = 64'hBF7AC516BE4DEE60;
            10'd480: raw_data = 64'hBF7B14BEBE47C5C2;
            10'd481: raw_data = 64'hBF7B61FCBE419B37;
            10'd482: raw_data = 64'hBF7BACCDBE3B6ECF;
            10'd483: raw_data = 64'hBF7BF531BE354098;
            10'd484: raw_data = 64'hBF7C3B28BE2F10A2;
            10'd485: raw_data = 64'hBF7C7EB0BE28DEFC;
            10'd486: raw_data = 64'hBF7CBFC9BE22ABB6;
            10'd487: raw_data = 64'hBF7CFE73BE1C76DE;
            10'd488: raw_data = 64'hBF7D3AACBE164083;
            10'd489: raw_data = 64'hBF7D7474BE1008B7;
            10'd490: raw_data = 64'hBF7DABCCBE09CF86;
            10'd491: raw_data = 64'hBF7DE0B1BE039502;
            10'd492: raw_data = 64'hBF7E1324BDFAB273;
            10'd493: raw_data = 64'hBF7E4323BDEE3876;
            10'd494: raw_data = 64'hBF7E70B0BDE1BC2E;
            10'd495: raw_data = 64'hBF7E9BC9BDD53DB9;
            10'd496: raw_data = 64'hBF7EC46DBDC8BD36;
            10'd497: raw_data = 64'hBF7EEA9DBDBC3AC3;
            10'd498: raw_data = 64'hBF7F0E58BDAFB680;
            10'd499: raw_data = 64'hBF7F2F9DBDA3308C;
            10'd500: raw_data = 64'hBF7F4E6DBD96A905;
            10'd501: raw_data = 64'hBF7F6AC7BD8A200A;
            10'd502: raw_data = 64'hBF7F84ABBD7B2B74;
            10'd503: raw_data = 64'hBF7F9C18BD621469;
            10'd504: raw_data = 64'hBF7FB10FBD48FB30;
            10'd505: raw_data = 64'hBF7FC38FBD2FE007;
            10'd506: raw_data = 64'hBF7FD397BD16C32C;
            10'd507: raw_data = 64'hBF7FE129BCFB49BA;
            10'd508: raw_data = 64'hBF7FEC43BCC90AB0;
            10'd509: raw_data = 64'hBF7FF4E6BC96C9B6;
            10'd510: raw_data = 64'hBF7FFB11BC490E90;
            10'd511: raw_data = 64'hBF7FFEC4BBC90F88;
            default: raw_data = 64'h3F80000000000000; // fallback: W^0 = 1+0j
        endcase
    end

    // --------------------------------------------------------
    // 4. Output Generation
    // --------------------------------------------------------
    always @(*) begin
        if (is_midpoint) begin
            // Hardcoded -1.0 (real = -1.0 -> 0xBF800000, imag = +0.0 -> 0x00000000)
            twiddle_out = 64'hBF80_0000_0000_0000;
        end else begin
            twiddle_out = raw_data;

            // Apply conjugate (flip the sign of the imaginary part)
            if (use_conjugate) begin
                if (twiddle_out[31:0] != 32'h0000_0000)
                    twiddle_out[31:0] = {~twiddle_out[31], twiddle_out[30:0]};
            end
        end
    end

endmodule
