// =============================================================================
// fft_pcpi_wrapper.v
//
// PicoRV32 PCPI co-processor wrapper for the mixed-precision 256-point FFT.
//
// Implements 5 CUSTOM-0 instructions (opcode 7'b0001011), selected by funct3.
// No memory-bus access, no DMA/burst engine, no multi-core select: this targets
// exactly one fixed, pre-synthesized core (mixed_fft_256_top), per the simplified
// scope agreed for this milestone. FFTCFG / FFTBFLY / multi-core select from the
// original 7-instruction sketch are intentionally dropped -- there is nothing for
// them to configure since precision/N are baked into mixed_fft_256_core at
// generation time.
//
// Instruction semantics (R-type fields: funct7|rs2|rs1|funct3|rd|opcode):
//
//   FFTLOAD   funct3=001   rs1 = packed complex FP8 sample {real[7:0],imag[7:0]}
//                          rs2 = sample index (0..255, natural order; the FFT
//                                top module's internal bit_reverse handles
//                                reordering)
//                          rd  = 0 (no result)
//             Pulses load_en for one cycle. Software issues this 256 times.
//
//   FFTSTORE  funct3=010   rs1 = sample index (0..255)
//                          rd  = packed complex FP8 result read back from the core
//             2-cycle handshake (memory has 1-cycle synchronous read latency).
//
//   FFTSTART  funct3=011   rs1/rs2/rd unused. Pulses `start` for one cycle and
//                          clears the sticky status_done flag.
//
//   FFTWAIT   funct3=100   rs1 = timeout in cycles (0 = wait forever)
//                          rd  = 1 if FFT completed, 0 if timed out
//             Blocking: holds pcpi_wait until core asserts done or timeout expires.
//
//   FFTSTATUS funct3=101   rd = {31'b0, status_done}  (non-blocking, 1 cycle)
//
// =============================================================================
`timescale 1ns/1ps

module fft_pcpi_wrapper (
    input  wire        clk,
    input  wire        rst_n,        // active-low, shared with mixed_fft_256_top's `rst`

    // PCPI slave port, wired directly to PicoRV32's pcpi_* ports
    input  wire        pcpi_valid,
    input  wire [31:0] pcpi_insn,
    input  wire [31:0] pcpi_rs1,
    input  wire [31:0] pcpi_rs2,
    output reg         pcpi_wr,
    output reg  [31:0] pcpi_rd,
    output reg         pcpi_wait,
    output reg         pcpi_ready
);

    // -------------------------------------------------------------------
    // Instruction decode
    // -------------------------------------------------------------------
    localparam OPCODE_CUSTOM0 = 7'b0001011;

    localparam F3_FFTLOAD   = 3'b001;
    localparam F3_FFTSTORE  = 3'b010;
    localparam F3_FFTSTART  = 3'b011;
    localparam F3_FFTWAIT   = 3'b100;
    localparam F3_FFTSTATUS = 3'b101;

    wire [6:0] opcode = pcpi_insn[6:0];
    wire [2:0] funct3 = pcpi_insn[14:12];

    wire is_custom0  = (opcode == OPCODE_CUSTOM0);
    wire is_fft_insn = pcpi_valid && is_custom0 &&
                        (funct3 == F3_FFTLOAD   || funct3 == F3_FFTSTORE ||
                         funct3 == F3_FFTSTART  || funct3 == F3_FFTWAIT  ||
                         funct3 == F3_FFTSTATUS);

    // -------------------------------------------------------------------
    // FFT core instance (mixed_fft_256_top, generated by fft_template_generator.py
    // for fft_size=256; unmodified)
    // -------------------------------------------------------------------
    reg         fft_start;
    wire        fft_done;
    reg         fft_load_en;
    reg  [7:0]  fft_load_addr;
    reg  [15:0] fft_load_data;
    reg         fft_unload_en;
    reg  [7:0]  fft_unload_addr;
    wire [15:0] fft_unload_data;

    mixed_fft_256_top u_fft (
        .clk        (clk),
        .rst        (rst_n),
        .start      (fft_start),
        .done       (fft_done),
        .load_en    (fft_load_en),
        .load_addr  (fft_load_addr),
        .load_data  (fft_load_data),
        .unload_en  (fft_unload_en),
        .unload_addr(fft_unload_addr),
        .unload_data(fft_unload_data)
    );

    // Sticky "completed" status: cleared by FFTSTART, set by core's `done` pulse.
    // This exists because the core's own `done` is only held for one cycle
    // before the top module's internal FSM drops it again -- software needs a
    // status bit that survives until the next FFTSTART.
    reg status_done;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            status_done <= 1'b0;
        else if (fft_start)
            status_done <= 1'b0;
        else if (fft_done)
            status_done <= 1'b1;
    end

    // -------------------------------------------------------------------
    // Control FSM
    // -------------------------------------------------------------------
    localparam S_IDLE      = 3'd0,
               S_STORE_CAP = 3'd1,
               S_WAIT_POLL = 3'd2;

    reg [2:0]  state;
    reg [31:0] timeout_cnt;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state         <= S_IDLE;
            pcpi_wr       <= 1'b0;
            pcpi_rd       <= 32'b0;
            pcpi_wait     <= 1'b0;
            pcpi_ready    <= 1'b0;
            fft_start     <= 1'b0;
            fft_load_en   <= 1'b0;
            fft_unload_en <= 1'b0;
            fft_load_addr <= 8'b0;
            fft_load_data <= 16'b0;
            fft_unload_addr <= 8'b0;
            timeout_cnt   <= 32'b0;
        end else begin
            // Defaults each cycle -- overridden below where needed.
            pcpi_ready    <= 1'b0;
            pcpi_wr       <= 1'b0;
            fft_start     <= 1'b0;
            fft_load_en   <= 1'b0;
            fft_unload_en <= 1'b0;

            case (state)
                // -----------------------------------------------------
                S_IDLE: begin
                    pcpi_wait <= 1'b0;
                    if (is_fft_insn) begin
                        case (funct3)
                            F3_FFTLOAD: begin
                                fft_load_en   <= 1'b1;
                                fft_load_addr <= pcpi_rs2[7:0];
                                fft_load_data <= pcpi_rs1[15:0];
                                pcpi_ready    <= 1'b1;
                                pcpi_wr       <= 1'b1;
                                pcpi_rd       <= 32'b0;
                            end

                            F3_FFTSTART: begin
                                fft_start  <= 1'b1;
                                pcpi_ready <= 1'b1;
                            end

                            F3_FFTSTATUS: begin
                                pcpi_ready <= 1'b1;
                                pcpi_wr    <= 1'b1;
                                pcpi_rd    <= {31'b0, status_done};
                            end

                            F3_FFTSTORE: begin
                                fft_unload_en   <= 1'b1;
                                fft_unload_addr <= pcpi_rs1[7:0];
                                pcpi_wait       <= 1'b1;
                                state           <= S_STORE_CAP;
                            end

                            F3_FFTWAIT: begin
                                if (status_done) begin
                                    pcpi_ready <= 1'b1;
                                    pcpi_wr    <= 1'b1;
                                    pcpi_rd    <= 32'h1;
                                end else begin
                                    pcpi_wait   <= 1'b1;
                                    timeout_cnt <= pcpi_rs1; // 0 = wait forever
                                    state       <= S_WAIT_POLL;
                                end
                            end

                            default: ; // not reached, gated by is_fft_insn
                        endcase
                    end
                end

                // -----------------------------------------------------
                // unload_data is valid the cycle after unload_addr/en assert
                // (mixed_dual_bank_memory_concurrent has 1-cycle synchronous read)
                S_STORE_CAP: begin
                    pcpi_ready <= 1'b1;
                    pcpi_wr    <= 1'b1;
                    pcpi_rd    <= {16'b0, fft_unload_data};
                    pcpi_wait  <= 1'b0;
                    state      <= S_IDLE;
                end

                // -----------------------------------------------------
                S_WAIT_POLL: begin
                    if (status_done) begin
                        pcpi_ready <= 1'b1;
                        pcpi_wr    <= 1'b1;
                        pcpi_rd    <= 32'h1;
                        pcpi_wait  <= 1'b0;
                        state      <= S_IDLE;
                    end else if (timeout_cnt == 32'h1) begin
                        pcpi_ready <= 1'b1;
                        pcpi_wr    <= 1'b1;
                        pcpi_rd    <= 32'h0; // timed out
                        pcpi_wait  <= 1'b0;
                        state      <= S_IDLE;
                    end else begin
                        if (timeout_cnt != 32'b0)
                            timeout_cnt <= timeout_cnt - 32'b1;
                        pcpi_wait <= 1'b1;
                    end
                end

                default: state <= S_IDLE;
            endcase
        end
    end

endmodule
