#!/usr/bin/env python3
"""
Generate the FP32 twiddle-factor ROM contents for the FP32 baseline FFT cores.

Produces 512 lines of 64-bit binary (one per ROM entry), matching the layout
that twiddle_factor_fp32 expects:

    [63:32] FP32 real   [31:0] FP32 imag

Entry k holds W_1024^k = exp(-j*2*pi*k/1024) for k = 0 .. 511.  The RTL derives
smaller N by scaling k, and covers the second half-plane by conjugation, so
only the first 512 entries are stored -- exactly like the existing 24-bit
unified ROM in verilog_sources/twiddles_1024.txt.

Rounding is round-to-nearest-even, matching the RTL arithmetic.

Lives directly in fp32_baseline/.  By default the ROM file is written to
fp32_baseline/source/twiddles_fp32_1024.txt, independent of the
directory the script is run from.

Also regenerates fp32_baseline/source/fp32_twiddle_rom.v as a fully
synthesizable, registered-case-statement ROM (mirroring the ASIC-friendly
approach used by verilog_sources/twiddle_rom_synthesizable.v for the
mixed-precision unified ROM) instead of an $readmemb-based memory. A
$readmemb ROM depends on a *relative* file path being present next to
whatever tool's working directory it happens to run from, which is fine for
iverilog simulation but is fragile for Yosys/OpenROAD synthesis runs -- the
case-statement form has no external file dependency at all, and the two
representations are generated from the exact same computed entries so they
can never drift apart.

Usage:
    python fp32_baseline/generate_fp32_twiddles.py
    python fp32_baseline/generate_fp32_twiddles.py --out some/other/file.txt
"""

import argparse
import math
import os
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT = os.path.join(HERE, "source", "twiddles_fp32_1024.txt")
DEFAULT_ROM_OUT = os.path.join(HERE, "source", "fp32_twiddle_rom.v")


def f64_to_fp32_bits(x: float) -> int:
    """IEEE 754 binary32 bit pattern for x, round-to-nearest-even."""
    packed = struct.pack(">f", x)          # ">f" is big-endian binary32
    return struct.unpack(">I", packed)[0]


def fp32_bits_to_float(bits: int) -> float:
    return struct.unpack(">f", struct.pack(">I", bits))[0]


def compute_entries(max_n: int):
    """Return (word_list, worst_err): word_list[k] is the 64-bit ROM word for
    W_max_n^k, k = 0 .. max_n/2 - 1."""
    entries = max_n // 2
    worst_err = 0.0
    words = []

    for k in range(entries):
        angle = -2.0 * math.pi * k / max_n
        re = math.cos(angle)
        im = math.sin(angle)

        re_bits = f64_to_fp32_bits(re)
        im_bits = f64_to_fp32_bits(im)

        # Normalise -0.0 to +0.0 so the ROM never stores a signed zero
        # (the RTL's conjugate logic keys off a non-zero imaginary field).
        if re_bits == 0x80000000:
            re_bits = 0x00000000
        if im_bits == 0x80000000:
            im_bits = 0x00000000

        err = max(abs(fp32_bits_to_float(re_bits) - re),
                  abs(fp32_bits_to_float(im_bits) - im))
        worst_err = max(worst_err, err)

        words.append((re_bits << 32) | im_bits)

    return words, worst_err


def generate(max_n: int, out_path: str) -> list:
    words, worst_err = compute_entries(max_n)

    out_dir = os.path.dirname(os.path.abspath(out_path))
    os.makedirs(out_dir, exist_ok=True)

    with open(out_path, "w") as f:
        for word in words:
            f.write(f"{word:064b}\n")

    print(f"Wrote {len(words)} FP32 twiddle entries to {out_path}")
    print(f"Worst-case quantisation error: {worst_err:.3e}")
    return words


ROM_MODULE_TEMPLATE = """\
// =============================================================================
// FP32 Twiddle Factor ROM -- synthesizable case-statement version
// =============================================================================
// AUTO-GENERATED by generate_fp32_twiddles.py -- do not hand-edit the ROM
// table below; re-run the generator instead.
//
// Mirrors twiddle_factor_unified in verilog_sources/twiddle_rom_synthesizable.v:
// same dynamic k-scaling for runtime N, same half-plane symmetry +
// conjugation, same hardcoded -1.0 midpoint. The stored word is 64-bit
// complex FP32 instead of the 24-bit unified FP8+FP4 word, and there is no
// PRECISION port.
//
// ROM word format: [63:32] FP32 Real, [31:0] FP32 Imag
//
// FIX (synthesis): replaced the $readmemb-based memory with a fully
// synthesizable registered-case ROM. All {num_entries} entries are sourced
// directly from twiddles_fp32_1024.txt (authoritative) via
// generate_fp32_twiddles.py. Yosys/OpenROAD infer this as a ROM mapped to
// library cells -- no external file dependency at synthesis time, no
// working-directory-relative path to get wrong.
//
// Conjugate symmetry: only k=0..{last_entry} are stored.
//   W_N^{{N-k}} = conj(W_N^k) -> second half handled by flipping the
//   imaginary sign bit. k={num_entries} (W=-1+0j) is hardcoded separately.
// =============================================================================

module twiddle_factor_fp32 #(
    parameter MAX_N      = {max_n},
    parameter ADDR_WIDTH = $clog2(MAX_N) + 1
)(
    input  [ADDR_WIDTH-1:0] k,            // Index k
    input  [ADDR_WIDTH-1:0] n,            // Current FFT size N
    output reg [63:0]       twiddle_out
);

    // --------------------------------------------------------
    // 1. Dynamic Scaling Logic
    // --------------------------------------------------------
    reg [ADDR_WIDTH-1:0] scaled_k;

    always @(*) begin
        case (n)
            1024: scaled_k = k;
            512:  scaled_k = {{k, 1'b0}};         // k * 2
            256:  scaled_k = {{k, 2'b00}};        // k * 4
            128:  scaled_k = {{k, 3'b000}};       // k * 8
            64:   scaled_k = {{k, 4'b0000}};      // k * 16
            32:   scaled_k = {{k, 5'b00000}};     // k * 32
            16:   scaled_k = {{k, 6'b000000}};    // k * 64
            8:    scaled_k = {{k, 7'b0000000}};   // k * 128
            4:    scaled_k = {{k, 8'b00000000}};  // k * 256
            2:    scaled_k = {{k, 9'b000000000}}; // k * 512
            default: scaled_k = 11'd0;
        endcase
    end

    // --------------------------------------------------------
    // 2. Symmetry Logic
    // --------------------------------------------------------
    reg        use_conjugate;
    reg [9:0]  rom_addr;       // Address within the 0-{last_entry} block
    reg        is_midpoint;

    always @(*) begin
        is_midpoint = 1'b0;

        if (scaled_k == {num_entries}) begin
            // 180 degrees is a boundary case
            is_midpoint   = 1'b1;
            rom_addr      = 0;
            use_conjugate = 1'b0;
        end
        else if (scaled_k > {last_entry}) begin
            // Second half (180 < angle < 360) -> Symmetry
            rom_addr      = {max_n} - scaled_k;
            use_conjugate = 1'b1;
        end
        else begin
            // First half (0 <= angle < 180)
            rom_addr      = scaled_k;
            use_conjugate = 1'b0;
        end
    end

    // --------------------------------------------------------
    // 3. ROM -- {num_entries} entries, combinational case statement.
    //    Yosys/synthesis infers this as a ROM, not flip-flops.
    // --------------------------------------------------------
    reg [63:0] raw_data;

    always @(*) begin
        case (rom_addr)
{rom_cases}
            default: raw_data = 64'h{fallback:016X}; // fallback: W^0 = 1+0j
        endcase
    end

    // --------------------------------------------------------
    // 4. Output Generation
    // --------------------------------------------------------
    always @(*) begin
        if (is_midpoint) begin
            // Hardcoded -1.0 (real = -1.0 -> 0xBF800000, imag = +0.0 -> 0x00000000)
            twiddle_out = 64'hBF80_0000_0000_0000;
        end else begin
            twiddle_out = raw_data;

            // Apply conjugate (flip the sign of the imaginary part)
            if (use_conjugate) begin
                if (twiddle_out[31:0] != 32'h0000_0000)
                    twiddle_out[31:0] = {{~twiddle_out[31], twiddle_out[30:0]}};
            end
        end
    end

endmodule
"""


def generate_synthesizable_rom(words: list, max_n: int, rom_out_path: str) -> None:
    num_entries = len(words)
    case_lines = "\n".join(
        f"            10'd{addr}: raw_data = 64'h{word:016X};"
        for addr, word in enumerate(words)
    )
    verilog = ROM_MODULE_TEMPLATE.format(
        max_n=max_n,
        num_entries=num_entries,
        last_entry=num_entries - 1,
        rom_cases=case_lines,
        fallback=words[0],
    )

    out_dir = os.path.dirname(os.path.abspath(rom_out_path))
    os.makedirs(out_dir, exist_ok=True)
    with open(rom_out_path, "w") as f:
        f.write(verilog)

    print(f"Wrote synthesizable {num_entries}-entry case ROM to {rom_out_path}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Generate the FP32 twiddle ROM.")
    ap.add_argument("--max-n", type=int, default=1024,
                    help="Largest FFT size the ROM must serve (default 1024)")
    ap.add_argument("--out", type=str, default=DEFAULT_OUT,
                    help="Output file (default: fp32_baseline/source/"
                         "twiddles_fp32_1024.txt)")
    ap.add_argument("--rom-out", type=str, default=DEFAULT_ROM_OUT,
                    help="Synthesizable ROM Verilog file (default: "
                         "fp32_baseline/source/fp32_twiddle_rom.v)")
    ap.add_argument("--skip-rom", action="store_true",
                    help="Only write the .txt table, skip regenerating the "
                         "synthesizable fp32_twiddle_rom.v")
    args = ap.parse_args()
    words = generate(args.max_n, args.out)
    if not args.skip_rom:
        generate_synthesizable_rom(words, args.max_n, args.rom_out)
